apiVersion: v1
kind: Service
metadata:
  labels:
    es.service: es-master-service
  name: es-master-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
    - name: "9300"
      port: 9300
      targetPort: 9300
  selector:
    node.type: es-node-master