apiVersion: v1
kind: Service
metadata:
  labels:
    es.service: kibana-service
  name: kibana-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
  selector:
    node.type: kibana-node