apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}
  
subjects:
- kind: ServiceAccount
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.appName }}
  apiGroup: rbac.authorization.k8s.io